runtime: custom
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always # Enable this when have ssl cert

runtime_config:
  jdk: openjdk8
  server: jetty9

manual_scaling:
  instances: 1
  
resources:
  cpu: 2
  memory_gb: 2.5

